'''You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"'''

from collections import Counter

# tc = O(n+m) and sc = O(n)
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        d = Counter(s)
        for i in t:
            if i in d and d[i] > 0:
                d[i] -= 1
            else:
                return i

# tc = O(n) and sc = O(1)       
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        ans = 0
        for i in range(len(s)):
            ans = ans ^ ord(s[i]) ^ ord(t[i])
        ans ^= ord(t[-1])
        return chr(ans)